### ISSUE TITLE
BrokenPipeError when batchsize is large

### ISSUE THREAD

**Issue by JackyWang2001** [google-research/fixmatch#75]
Hi, authors. Thanks for your inspiring work.
I am trying to run the code with a larger batch size. However, I was able to run it with batchsize<=1024, where the GPU used dedicated memory was only 2% and it was inefficient. But when batchsize>=2048, a BrokenPipeError from `python/multiprocessing` occurs. I changed batch by chaging `FLAGS.set_default('batch', 1024)` in `fixmatch.py` and tried two commands:
```
CUDA_VISIBLE_DEVICES=0 python fixmatch.py --filters=32 --dataset=cifar10.3@40-1 --train_dir ./experiments/fixmatch
```
and multi-gpu 
```
CUDA_VISIBLE_DEVICES=0,1 python fixmatch.py --filters=32 --dataset=cifar10.3@40-1 --train_dir ./experiments/fixmatch
```
Both gave the similar error message as the following
```
:~/Documents/FixMatch$ CUDA_VISIBLE_DEVICES=0,1 python fixmatch.py --filters=32 --dataset=cifar10.3@40-1 --train_dir ./experiments/fixmatch
------------------------------------ Config ------------------------------------
train_dir ./experiments/fixmatch/cifar10.d.d.d.3@40-1/CTAugment_depth2_th0.80_decay0.990/FixMatch_archresnet_batch8192_confidence0.95_filters32_lr0.03_nclass10_repeat4_scales3_uratio7_wd0.0005_wu1.0
Model                            FixMatch
Dataset                          cifar10.d.d.d.3@40-1
arch                             resnet
batch                            8192
confidence                       0.95
filters                          32
lr                               0.03
nclass                           10
repeat                           4
scales                           3
uratio                           7
wd                               0.0005
wu                               1.0
------------------------------------ Model -------------------------------------
classify/conv2d/kernel:0                     432     (3, 3, 3, 16)
classify/conv2d/bias:0                        16             (16,)
classify/batch_normalization/gamma:0          16             (16,)
classify/batch_normalization/beta:0           16             (16,)
classify/conv2d_1/kernel:0                  4608    (3, 3, 16, 32)
classify/conv2d_1/bias:0                      32             (32,)
classify/batch_normalization_1/gamma:0        32             (32,)
classify/batch_normalization_1/beta:0         32             (32,)
classify/conv2d_2/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_2/bias:0                      32             (32,)
classify/conv2d_3/kernel:0                   512    (1, 1, 16, 32)
classify/conv2d_3/bias:0                      32             (32,)
classify/batch_normalization_2/gamma:0        32             (32,)
classify/batch_normalization_2/beta:0         32             (32,)
classify/conv2d_4/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_4/bias:0                      32             (32,)
classify/batch_normalization_3/gamma:0        32             (32,)
classify/batch_normalization_3/beta:0         32             (32,)
classify/conv2d_5/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_5/bias:0                      32             (32,)
classify/batch_normalization_4/gamma:0        32             (32,)
classify/batch_normalization_4/beta:0         32             (32,)
classify/conv2d_6/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_6/bias:0                      32             (32,)
classify/batch_normalization_5/gamma:0        32             (32,)
classify/batch_normalization_5/beta:0         32             (32,)
classify/conv2d_7/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_7/bias:0                      32             (32,)
classify/batch_normalization_6/gamma:0        32             (32,)
classify/batch_normalization_6/beta:0         32             (32,)
classify/conv2d_8/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_8/bias:0                      32             (32,)
classify/batch_normalization_7/gamma:0        32             (32,)
classify/batch_normalization_7/beta:0         32             (32,)
classify/conv2d_9/kernel:0                  9216    (3, 3, 32, 32)
classify/conv2d_9/bias:0                      32             (32,)
classify/batch_normalization_8/gamma:0        32             (32,)
classify/batch_normalization_8/beta:0         32             (32,)
classify/conv2d_10/kernel:0                18432    (3, 3, 32, 64)
classify/conv2d_10/bias:0                     64             (64,)
classify/batch_normalization_9/gamma:0        64             (64,)
classify/batch_normalization_9/beta:0         64             (64,)
classify/conv2d_11/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_11/bias:0                     64             (64,)
classify/conv2d_12/kernel:0                 2048    (1, 1, 32, 64)
classify/conv2d_12/bias:0                     64             (64,)
classify/batch_normalization_10/gamma:0       64             (64,)
classify/batch_normalization_10/beta:0        64             (64,)
classify/conv2d_13/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_13/bias:0                     64             (64,)
classify/batch_normalization_11/gamma:0       64             (64,)
classify/batch_normalization_11/beta:0        64             (64,)
classify/conv2d_14/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_14/bias:0                     64             (64,)
classify/batch_normalization_12/gamma:0       64             (64,)
classify/batch_normalization_12/beta:0        64             (64,)
classify/conv2d_15/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_15/bias:0                     64             (64,)
classify/batch_normalization_13/gamma:0       64             (64,)
classify/batch_normalization_13/beta:0        64             (64,)
classify/conv2d_16/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_16/bias:0                     64             (64,)
classify/batch_normalization_14/gamma:0       64             (64,)
classify/batch_normalization_14/beta:0        64             (64,)
classify/conv2d_17/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_17/bias:0                     64             (64,)
classify/batch_normalization_15/gamma:0       64             (64,)
classify/batch_normalization_15/beta:0        64             (64,)
classify/conv2d_18/kernel:0                36864    (3, 3, 64, 64)
classify/conv2d_18/bias:0                     64             (64,)
classify/batch_normalization_16/gamma:0       64             (64,)
classify/batch_normalization_16/beta:0        64             (64,)
classify/conv2d_19/kernel:0                73728   (3, 3, 64, 128)
classify/conv2d_19/bias:0                    128            (128,)
classify/batch_normalization_17/gamma:0      128            (128,)
classify/batch_normalization_17/beta:0       128            (128,)
classify/conv2d_20/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_20/bias:0                    128            (128,)
classify/conv2d_21/kernel:0                 8192   (1, 1, 64, 128)
classify/conv2d_21/bias:0                    128            (128,)
classify/batch_normalization_18/gamma:0      128            (128,)
classify/batch_normalization_18/beta:0       128            (128,)
classify/conv2d_22/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_22/bias:0                    128            (128,)
classify/batch_normalization_19/gamma:0      128            (128,)
classify/batch_normalization_19/beta:0       128            (128,)
classify/conv2d_23/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_23/bias:0                    128            (128,)
classify/batch_normalization_20/gamma:0      128            (128,)
classify/batch_normalization_20/beta:0       128            (128,)
classify/conv2d_24/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_24/bias:0                    128            (128,)
classify/batch_normalization_21/gamma:0      128            (128,)
classify/batch_normalization_21/beta:0       128            (128,)
classify/conv2d_25/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_25/bias:0                    128            (128,)
classify/batch_normalization_22/gamma:0      128            (128,)
classify/batch_normalization_22/beta:0       128            (128,)
classify/conv2d_26/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_26/bias:0                    128            (128,)
classify/batch_normalization_23/gamma:0      128            (128,)
classify/batch_normalization_23/beta:0       128            (128,)
classify/conv2d_27/kernel:0               147456  (3, 3, 128, 128)
classify/conv2d_27/bias:0                    128            (128,)
classify/batch_normalization_24/gamma:0      128            (128,)
classify/batch_normalization_24/beta:0       128            (128,)
classify/dense/kernel:0                     1280         (128, 10)
classify/dense/bias:0                         10             (10,)

Total                                    1469642                  
--------------------------------------------------------------------------------
Caching test examples: 10000it [00:01, 7306.87it/s]
Caching valid examples: 1it [00:00,  4.00it/s]
Caching train_labeled examples: 40it [00:00, 159.60it/s]
Epoch 1/1024:   0%|                                                                                                  | 0/65536 [00:00<?, ?img/s]terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Fatal Python error: Aborted

Thread 0x00007f20f6ffd700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429 in _call_tf_sessionrun
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341 in _run_fn
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356 in _do_call
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350 in _do_run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173 in _run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950 in run
  File "/home/jpl/Documents/FixMatch/cta/lib/train.py", line 92 in eval_stats
  File "/home/jpl/Documents/FixMatch/libml/train.py", line 247 in gen_stats
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209 in __call__

Thread 0x00007f20b4ff9700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429 in _call_tf_sessionrun
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341 in _run_fn
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356 in _do_call
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350 in _do_run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173 in _run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950 in run
  File "/home/jpl/Documents/FixMatch/cta/lib/train.py", line 92 in eval_stats
  File "/home/jpl/Documents/FixMatch/libml/train.py", line 247 in gen_stats
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209 in __call__

Thread 0x00007f24d183b700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 379 in _recv
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 411 in _recv_bytes
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 250 in recv
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 463 in _handle_results
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 864 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f24cf03a700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368 in _send
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 397 in _send_bytes
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 206 in send
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 424 in _handle_tasks
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 864 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f24cc839700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 406 in _handle_workers
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 864 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f234cff9700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 295 in wait
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/queue.py", line 164 in get
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 159 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f209cff9700 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 299 in wait
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 551 in wait
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tqdm/_monitor.py", line 60 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f262f633180 (most recent call first):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429 in _call_tf_sessionrun
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341 in _run_fn
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356 in _do_call
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350 in _do_run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173 in _run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1169 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1411 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1338 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1252 in run
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 754 in run
  File "/home/jpl/Documents/FixMatch/cta/lib/train.py", line 69 in train_step
  File "fixmatch.py", line 79 in train
  File "fixmatch.py", line 160 in main
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/absl/app.py", line 258 in _run_main
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/site-packages/absl/app.py", line 312 in run
  File "fixmatch.py", line 177 in <module>
Aborted (core dumped)
(fixmatch) jpl@lambda-dual:~/Documents/FixMatch$ Process ForkPoolWorker-1:
Process ForkPoolWorker-2:
Process ForkPoolWorker-5:
Process ForkPoolWorker-3:
Process ForkPoolWorker-4:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
Traceback (most recent call last):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
BrokenPipeError: [Errno 32] Broken pipe
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)

During handling of the above exception, another exception occurred:

  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 398, in _send_bytes
    self._send(buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)

During handling of the above exception, another exception occurred:

BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
Traceback (most recent call last):
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
BrokenPipeError: [Errno 32] Broken pipe
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/home/jpl/anaconda3/envs/fixmatch/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by JackyWang2001** [comment]
aware that tf does not detect my gpu
